### ISSUE TITLE
Workshop checklist

### ISSUE THREAD

**Issue by smcclatchy** [TheJacksonLaboratory/2018-11-06-jax#1]
**At the start** of the workshop:
- [ ] Write the following participants' to-do list on the whiteboard.

1. Go to the workshop website at (provide workshop website URL).

1. Complete the pre-workshop survey on the workshop website.

1. Locate the link to the collaborative document (etherpad) beneath the schedule, or go directly to (provide etherpad URL).

1. Enter your name and choose a color at upper right of etherpad.

1. Sign in on the Participants list. Complete the pre-workshop survey if you haven't done so already.

1. Locate the lesson material at (provide lesson website URL), or use the links within the schedule.

- [ ] Pass out sticky notes.

- [ ] Help people who arrive late to become oriented with the workshop website, etherpad, and lesson website by pointing them to the to-do list on the whiteboard.

**During** the workshop:

- [ ] Take attendance by cross-checking the etherpad participant list and the registrant list. Also check for name tags that were not claimed. Count the number of participants in the room and compare to attendance list you've made to make sure numbers are the same. Do this for each day. Send the attendance list with names to Sue, and send the number for each day to Carpentries admin.

- [ ] Quietly help people who have installation or startup issues, or who need help with an exercise. 

- [ ] Keep the flow of the workshop moving by making sure that the instructor doesn't need to stop teaching in order to help others. Helpers and non-teaching instructors can take care of participants.

- [ ] Copy and paste each exercise in the etherpad as the instructor announces them.

- [ ] Remind participants to use sticky notes if they need help, or when they are finished with an exercise.

**Before lunch** and **before the end of each day** of the workshop:

- [ ] Write the following prompts on the whiteboard so that participants can provide positive and negative feedback on their sticky notes.

1. Sample positive prompts: What is the most important thing that you learned today? Or: What new skill are you most excited about using?

1. Sample negative”prompts: Write down one thing that is confusing and you’d like clarification on. Or: What is one specific question you have about the material?

Over lunch and before the second day starts, instructors can read through the minute cards and look for patterns. At the start of day two and each afternoon, the instructors take a few minutes to address commonly raised issues with the whole class. The non-teaching instructors and helpers can also type answers to the questions in the Etherpad.

**At the end** of the workshop:

- [ ] Write the post-workshop survey URL on the whiteboard, or direct people to the link on the workshop website. It's important to get feedback from people while they're still in the room. It's much harder to get it once they've left.

- [ ] Send a follow-up e-mail to participants requesting that they complete the post-workshop survey if they haven't done so already.
